### ISSUE TITLE
current-user has the potential to not be defined

### ISSUE THREAD

**Issue by tdegrunt** [entdec/signum#23]
See also the SignalController:
```ruby
# signals = Signum.config.current_user.call.signals.where.not(state: "closed") // current_user is nil when called from an api
```

This is happening because we a) use ActionController::API, though we can just use ApplicationController and b) Signum's application controller doesn't use the base_controller configuration.

**Comment by rparse** [comment]
PR created - https://github.com/entdec/signum/pull/24

**Comment by sanderhelsloot** [comment]
Signum messages and notification functionality work as expected.
