### ISSUE TITLE
Some dotting the i's and crossing the t's needed

### ISSUE THREAD

**Issue by tdegrunt** [entdec/signum#7]
We need to do some fine tunining:

* [x] Add attr_readers for use in component.html.slim (remove use of @signals etc)
* [x] Move frontend controllers inside the component folder, rename attributes in HTML,  and load them using a block to frontend/index.js like so:
```javascript
    componentControllers
      .keys()
      .map((key) => {
        // Take the last part (before component_controller) of the path as the name
        const [_, name] = /([^/]+)\/component_controller\.js$/.exec(key)
        return [name, componentControllers(key).default]
      })
      .forEach(([name, controller]) => {
        let identifier = `signum-${name.replace(/_/g, "-")}`
        this.application.register(identifier, controller)
      })
```

* [x] Put full notification-body inside the notification drawer (use new component)
* [x] Render notification-drawer items using with_collection / with_collection_parameter, see https://viewcomponent.org/guide/collections.html#with_collection_parameter
* [x] Allow the notification-drawer to scroll and put 25 last notifications in place
* [x] Don't show closed notifications
* [x] Remove closed notifications from the DOM (use remove https://turbo.hotwired.dev/handbook/streams)
* [x] Don't open the notification drawer if there are no notifications, see the gray bar:

<img width="409" alt="Screenshot 2024-02-26 at 08 32 50" src="https://github.com/entdec/signum/assets/46554/969680ab-120d-4bdd-9551-3d517bd18a2d">

* [x] Additionally signum gained a way to add attachments to signals, so we can present the user with exports/import results - adding attachments will touch the record, so updates should happen always, except for changes to the state (closed mostly).
* [x] Remove use of Signum::SendSignalsJob, this can be replaced by `broadcast_refreshes` (see https://rubydoc.info/github/hotwired/turbo-rails/main/Turbo/Broadcastable)
* [x] Grab the configuration.rb from importo and replace signum's configuration with it.
* [x] Add a icons option to the configuration (hash) which allows users to change the icons we use for success/error/info as well as the bell icons. Assume fontawesome, but not icon type/style.

* [x] Finetune looks a bit: title and body text and icon. Also links could use a small icon (fa-link), attachments get a paperclip. We need a bit more distance between body and the attachment (see third screenshot).
 
<img width="426" alt="Screenshot 2024-02-26 at 08 59 19" src="https://github.com/entdec/signum/assets/46554/cb0c32ca-5e87-4306-8854-4682b11125e4">

<img width="412" alt="Screenshot 2024-02-26 at 09 00 14" src="https://github.com/entdec/signum/assets/46554/3324fee7-1867-4f7c-a3c6-6d643b7c5d67">

<img width="463" alt="Screenshot 2024-02-26 at 09 05 06" src="https://github.com/entdec/signum/assets/46554/f28d0cdc-e410-4b83-ac6f-d4e3a3737459">

* [x] Remove the counts and percentages from the progressbar (maybe make it optional), make it a bit smaller and primary color - white counts?

<img width="426" alt="Screenshot 2024-02-26 at 08 59 19" src="https://github.com/entdec/signum/assets/46554/cb0c32ca-5e87-4306-8854-4682b11125e4">

See: https://flowbite.com/docs/components/progress/

Perhaps best to make this a satis component?

<img width="817" alt="Screenshot 2024-02-26 at 10 12 28" src="https://github.com/entdec/signum/assets/46554/bcc8c5bb-6e38-44b4-ba4e-44706db8a946">

We'll do the following in a separate ticket:

* [ ] #9

**Comment by sanderhelsloot** [comment]
As shown below, displaying the msgs 'Importing...' and 'Completed...', do not correspond with the progress bar anymore while the Download button returns a 404.

![Screenshot 2024-02-29 at 11 27 53](https://github.com/entdec/signum/assets/93649153/74dc10ef-89bc-4e16-b22c-cb710a6823eb)

![Screenshot 2024-02-29 at 11 27 43](https://github.com/entdec/signum/assets/93649153/d9892a45-1663-4550-9054-e7fc36b7987e)

![Screenshot 2024-02-29 at 11 50 19](https://github.com/entdec/signum/assets/93649153/16487e29-9026-4682-ae23-02dd583b0368)

**Comment by WaQasRPL** [comment]
Apart from one point stating "Sticky notifications are not added to the screen after refresh, can this be fixed?", rest are all completed.
this point require some core changes to the way turbo-rails is setup, which wont be possible currently. Already informed Tom about it.

PRs created

https://github.com/boxture/oms/pull/3839
https://github.com/entdec/signum/pull/8

**Comment by tdegrunt** [comment]
* [ ] There's a distinction in marking "read" and closing the ticket in the tray, I think we should remove the click (mark as read).

* [ ] When you click all notifications away but the last one. And then click away the last, the tray shows this line:
![Screenshot 2024-03-05 at 17 06 24](https://github.com/entdec/signum/assets/46554/1e8fb19c-fede-4819-ab69-7f42444c9b0a)

![Screenshot 2024-03-05 at 17 06 43](https://github.com/entdec/signum/assets/46554/69f31d6f-3755-4cbc-9280-18699d33e0d9)

* [ ]  Refreshing will then show new ones. Also two bells. Only one bell should be seen:
![Screenshot 2024-03-05 at 17 07 06](https://github.com/entdec/signum/assets/46554/6c40d84c-b7b1-4f12-a0b4-95c964de2bbf)

* [ ] Icon colors seem to be removed, perhaps make this configuration too?

### Possibly in different ticket, depending on the complexity:

* [ ] Currently you use an API controller, but if we use the signal controller with destroy with a turbo stream, which also pulls in new notifications.

Use @rails/request.js:
```javascript
import { delete } from '@rails/request.js'
  markRead (event) {
    let url = this.ourUrl // get url from notification body? and call delete on that?

    post(url, {
      responseKind: 'turbo-stream'
    }).then(() => {
      // do other magic, the turbo stream should pick things up based on the 
    })
  }
```

destroy.turbo_stream.slim:
```slim
= turbo_stream.update "css-selector" do
  | slim here

= turbo_stream.update "css-selector" do
  | slim here

```

**Comment by sanderhelsloot** [comment]
As discussed with Tom, we would like to add the signum msgs, with the following icon's.

(https://fontawesome.com/icons/circle-check?f=classic&s=solid)
(https://fontawesome.com/icons/circle-xmark?f=classic&s=solid)
https://fontawesome.com/icons/circle-info?f=classic&s=solid

Circle check requires to be green.
Circle xmark required to be red.
Circle info required to be orange.

**Comment by WaQasRPL** [comment]
PR created
https://github.com/entdec/signum/pull/11

I have skipped the last point in the comment due to its complexity and the amount of changes would be required as we initiate stream from backend, not on demand.

**Comment by tdegrunt** [comment]
Bell is not showing as ringing when there are "unread"/"unclosed" notifications:
<img width="490" alt="Screenshot 2024-03-06 at 16 26 26" src="https://github.com/entdec/signum/assets/46554/4b3391e4-afe1-4a15-851c-23be11482d15">

The close icon has too little margin from the right side of the notification too as compared to:

<img width="447" alt="Screenshot 2024-03-06 at 16 27 14" src="https://github.com/entdec/signum/assets/46554/b761db9f-699f-4a16-9bf3-a0c19a67885e">

It should be a bit more "roomy" / "wider"

**Comment by sanderhelsloot** [comment]
I would not expect the information icon's in the cases below.

Importing sales order.xlsx = informational
Completed import of sales order.xlsx = a circle-check
Warning import of sales order = triangle-exclamation (if it partially failed - e.g. duplicate lines)
Failed import of sales order.xlsx = square-mark (if non of the lines are imported)

![Screenshot 2024-03-07 at 13 33 22](https://github.com/entdec/signum/assets/93649153/b47db684-82e6-4a46-b1c6-f18352b31f47)
![Screenshot 2024-03-07 at 13 31 07](https://github.com/entdec/signum/assets/93649153/9eae3a2e-98b8-4af3-a1f3-3fccc6dc79f8)

**Comment by WaQasRPL** [comment]
PRs created for the above two comments

https://github.com/boxture/server/pull/3914
https://github.com/entdec/signum/pull/13

**Comment by sanderhelsloot** [comment]
The signum messages are displayed properly as expected. Warning, success, failure and informational messages are displayed for the scenario's.

**Comment by sanderhelsloot** [comment]
![Screenshot 2024-03-19 at 16 23 00](https://github.com/entdec/signum/assets/93649153/fd9f4f05-31f4-4c8f-8ab1-66644a1b51c8)
